//universal
export const FETCH_TICKETS = "FETCH_TICKETS"
export const FETCH_TICKETS_SUCCESS = "FETCH_TICKETS_SUCCESS"
export const FETCH_TICKETS_FAIL = "FETCH_TICKETS_FAIL"

export const CAST_VOTE = "CAST_VOTE"

//creator
export const CREATE_TICKET = "CREATE_TICKET"
export const DELETE_TICKET = "DELETE_TICKET"

//shareable
export const GENERATE_SHAREABLE_LINK = "GENERATE_SHAREABLE_LINK"